# statically link the C runtime so the executable does not depend on
# that shared/dynamic library
[target.'cfg(all(target_env = "msvc", target_os = "windows"))']
rustflags = ["-C", "target-feature=+crt-static"]