name: CI

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  COVERAGE_THRESHOLD: 40

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@fb51252c7ba57d633bc668f941da052e410add48 # v1.13.0
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl1-mesa-dev ttf-mscorefonts-installer libfontconfig-dev

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check formatting
        uses: actions-rust-lang/setup-rust-toolchain@fb51252c7ba57d633bc668f941da052e410add48 # v1.13.0
      - run: cargo fmt --all -- --check

      - name: Run clippy
        uses: actions-rust-lang/setup-rust-toolchain@fb51252c7ba57d633bc668f941da052e410add48 # v1.13.0
      - run: cargo clippy -- -D warnings

      - name: Check build
        uses: actions-rust-lang/setup-rust-toolchain@fb51252c7ba57d633bc668f941da052e410add48 # v1.13.0
      - run: cargo check --all-features

  test-and-coverage:
    name: Test and Coverage
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@fb51252c7ba57d633bc668f941da052e410add48 # v1.13.0
      with:
        toolchain: stable
        override: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl1-mesa-dev ttf-mscorefonts-installer libfontconfig-dev

    - name: Install cargo-tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Run tests with coverage
      run: |
        cargo tarpaulin --verbose --all-features --workspace --timeout 120 \
          --exclude-files src/main.rs \
          --out xml --output-dir coverage

    - name: Check coverage threshold
      run: |
        COVERAGE=$(cargo tarpaulin --all-features --workspace --timeout 120 --exclude-files src/main.rs | grep -oP '\K[0-9.]+% coverage')
        echo "Current coverage: ${COVERAGE}%"
        echo "Required coverage: ${COVERAGE_THRESHOLD}%"
        if (( $(echo "${COVERAGE} < ${COVERAGE_THRESHOLD}" | bc -l) )); then
          echo "❌ Coverage ${COVERAGE}% is below threshold ${COVERAGE_THRESHOLD}%"
          exit 1
        else
          echo "✅ Coverage ${COVERAGE}% meets threshold ${COVERAGE_THRESHOLD}%"
        fi